### ISSUE TITLE
Any plans of reviving this?

### ISSUE THREAD

**Issue by ugjka** [jonas747/cleverbot#2]
Seems to be broken...

**Comment by mrmayfield** [comment]
+1

**Comment by jonas747** [comment]
Something seems to have changed, dunno what, you can try looking yourself but i don't have time atm

**Comment by mrmayfield** [comment]
Okay sounds good. Yeah I'll probably put in a pull request this upcoming weekend.

**Comment by lmas** [comment]
You need to grab a cookie from the homepage first, before it will let you in. See https://github.com/folz/cleverbot.py/issues/13. Works perfectly once you have that cookie.

**Comment by jonas747** [comment]
I hardcoded it in since it looks like it's just a static cookie that's the same for everyone

**Comment by lmas** [comment]
Looks like the cleverbot guys did something again. Getting a `404 Not Found` now when calling `Ask()`, guess they shut it down.

**Comment by jonas747** [comment]
Yup looks like so, i'm trying to figure out what they require though

**Comment by ugjka** [comment]
I did my own wrapper https://github.com/ugjka/cleverbot-go/blob/master/cleverbot.go
I reused some parts of your code.

**Comment by jonas747** [comment]
Nice

**Comment by jogramming** [comment]
I added your lib in my readme, to redirect people to it.

**Comment by ugjka** [comment]
Thanks :+1:
